version: "3.8"

services:
  db:
    image: postgres:15
    ports:
      - 5434:5434
    networks:
      - backend
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB

networks:
  backend: