version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: database
    ports:
      - 5434:5432
    volumes:
      - "./backend/data:/var/lib/postgresql"
    networks:
      - backend
    env_file:
      - .docker.env
      
networks:
  backend:

volumes:
  postgres:
    driver: local
    name: database
    driver_opts:
      type: none
      o: bind
      device: ./backend/data