version: "3.8"

services:

  database:
    image: postgres:15
    container_name: database
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - "./database/data:/var/lib/postgresql"
    networks:
      - database
    env_file:
      - .env
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: on-failure
    depends_on:
      - database
    ports:
      - 5050:5050
    networks:
      - database
    env_file:
      - .env
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - 3000:3000
    volumes:
      - "./frontend/src:/app/frontend/src"
    networks:
      - frontend
      - backend
    env_file:
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    depends_on:
      - database
    ports: 
      - 7000:7000
    volumes:
      - "./backend/src:/app/backend/src"
    networks:
      - backend
      - frontend
      - database
    env_file:
      - .env
    environment:
      POSTGRES_HOST: database


volumes:
  database:
    driver: local
    name: database
    driver_opts:
      type: none
      o: bind
      device: ./database/data

networks:
  database:

  backend:

  frontend:
