version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: database
    ports:
      - 5434:5432
    volumes:
      - "./backend/data:/var/lib/postgresql"
    networks:
      - backend
    env_file:
      - .env
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 5050:80
    networks:
      - backend
    env_file:
      - .env
  
  frontend:
    build: ./requirements/
    container_name: frontend
    restart: always
    ports: 
      - 3000:3000
    volumes:
      - "./frontend/:/frontend/"
    networks:
      - frontend

volumes:
  postgres:
    driver: local
    name: database
    driver_opts:
      type: none
      o: bind
      device: ./backend/data

  frontend:
    driver: local
    name: front_srcs
    driver_opts:
      type: none
      o: bind
      device: ./frontend

networks:
  backend:

  frontend:
