version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres
    ports:
      - 5434:5432
    networks:
      - backend
    env_file:
      - .docker.env
      
networks:
  backend: