version: "3.8"

services:

  database:
    image: postgres:15
    container_name: database
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - "./backend/data:/var/lib/postgresql/data"
    networks:
      - database
    env_file:
      - .env
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: on-failure
    depends_on:
      - database
    ports:
      - 5050:80
    networks:
      - database
    env_file:
      - .env
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    volumes:
      - "./frontend:/frontend"
      - "/frontend/node_modules"
    depends_on:
      - backend
    ports:
      - 3000:3000
      
    networks:
      - frontend
      - backend
    env_file:
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    volumes:
      - "./backend:/backend"
      - "/backend/node_modules"
    depends_on:
      - database
    ports: 
      - 7000:7000
    networks:
      - backend
      - frontend
      - database
    env_file:
      - .env
    environment:
      POSTGRES_HOST: database


volumes:
  database:
    driver: local
    name: database
    driver_opts:
      type: none
      o: bind
      device: ./backend/database

networks:
  database:

  backend:

  frontend: